// SPDX-FileCopyrightText: Copyright The Miniflux Authors. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

package database // import "miniflux.app/v2/internal/database"

import (
	"database/sql"
)

// schemaVersion is derived from the number of migrations.
//
// picoflux ships a single consolidated SQLite baseline schema instead of the
// 132 incremental PostgreSQL migrations used by upstream miniflux. The schema
// was generated by applying every upstream migration against PostgreSQL,
// dumping the resulting structure, and translating it to SQLite:
//
//   - SERIAL / sequences        -> INTEGER PRIMARY KEY AUTOINCREMENT
//   - bigint                    -> INTEGER (SQLite integers are 64-bit)
//   - ENUM types                -> TEXT with CHECK constraints
//   - timestamptz / now()       -> TIMESTAMP / CURRENT_TIMESTAMP
//   - bytea                     -> BLOB
//   - jsonb / hstore            -> TEXT (validated with json_valid)
//   - text[] (tags)             -> TEXT holding a JSON array
//   - inet                      -> TEXT
//   - tsvector + GIN index      -> FTS5 virtual table + sync triggers
//
// The schema version table was replaced by "PRAGMA user_version".
var schemaVersion = len(migrations)

var migrations = []func(tx *sql.Tx) error{
	func(tx *sql.Tx) error {
		_, err := tx.Exec(schemaSQLite)
		return err
	},
}

const schemaSQLite = `
CREATE TABLE users (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	username TEXT NOT NULL,
	password TEXT,
	is_admin INTEGER DEFAULT 0,
	language TEXT DEFAULT 'en_US',
	timezone TEXT DEFAULT 'UTC',
	theme TEXT DEFAULT 'light_serif',
	last_login_at TIMESTAMP,
	entry_direction TEXT DEFAULT 'asc' CHECK (entry_direction IN ('asc','desc')),
	keyboard_shortcuts INTEGER DEFAULT 1,
	entries_per_page INTEGER DEFAULT 100,
	show_reading_time INTEGER DEFAULT 1,
	entry_swipe INTEGER DEFAULT 1,
	stylesheet TEXT NOT NULL DEFAULT '',
	google_id TEXT NOT NULL DEFAULT '',
	openid_connect_id TEXT NOT NULL DEFAULT '',
	display_mode TEXT DEFAULT 'standalone' CHECK (display_mode IN ('fullscreen','standalone','minimal-ui','browser')),
	entry_order TEXT DEFAULT 'published_at' CHECK (entry_order IN ('published_at','created_at')),
	default_reading_speed INTEGER DEFAULT 265,
	cjk_reading_speed INTEGER DEFAULT 500,
	default_home_page TEXT DEFAULT 'unread',
	categories_sorting_order TEXT NOT NULL DEFAULT 'unread_count',
	gesture_nav TEXT DEFAULT 'tap',
	mark_read_on_view INTEGER DEFAULT 1,
	media_playback_rate REAL DEFAULT 1,
	block_filter_entry_rules TEXT NOT NULL DEFAULT '',
	keep_filter_entry_rules TEXT NOT NULL DEFAULT '',
	mark_read_on_media_player_completion INTEGER DEFAULT 0,
	custom_js TEXT NOT NULL DEFAULT '',
	external_font_hosts TEXT NOT NULL DEFAULT '',
	always_open_external_links INTEGER DEFAULT 0,
	open_external_links_in_new_tab INTEGER DEFAULT 1,
	UNIQUE (username)
);

CREATE UNIQUE INDEX users_google_id_idx ON users (google_id) WHERE google_id <> '';
CREATE UNIQUE INDEX users_openid_connect_id_idx ON users (openid_connect_id) WHERE openid_connect_id <> '';

CREATE TABLE categories (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	user_id INTEGER NOT NULL,
	title TEXT NOT NULL,
	hide_globally INTEGER NOT NULL DEFAULT 0,
	UNIQUE (user_id, title),
	FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE feeds (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	user_id INTEGER NOT NULL,
	category_id INTEGER NOT NULL,
	title TEXT NOT NULL,
	feed_url TEXT NOT NULL,
	site_url TEXT NOT NULL,
	checked_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	etag_header TEXT DEFAULT '',
	last_modified_header TEXT DEFAULT '',
	parsing_error_msg TEXT DEFAULT '',
	parsing_error_count INTEGER DEFAULT 0,
	scraper_rules TEXT DEFAULT '',
	rewrite_rules TEXT DEFAULT '',
	crawler INTEGER DEFAULT 0,
	username TEXT DEFAULT '',
	password TEXT DEFAULT '',
	user_agent TEXT DEFAULT '',
	disabled INTEGER DEFAULT 0,
	next_check_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	ignore_http_cache INTEGER DEFAULT 0,
	fetch_via_proxy INTEGER DEFAULT 0,
	blocklist_rules TEXT NOT NULL DEFAULT '',
	keeplist_rules TEXT NOT NULL DEFAULT '',
	allow_self_signed_certificates INTEGER NOT NULL DEFAULT 0,
	cookie TEXT DEFAULT '',
	hide_globally INTEGER NOT NULL DEFAULT 0,
	url_rewrite_rules TEXT NOT NULL DEFAULT '',
	no_media_player INTEGER DEFAULT 0,
	apprise_service_urls TEXT DEFAULT '',
	disable_http2 INTEGER DEFAULT 0,
	description TEXT DEFAULT '',
	ntfy_enabled INTEGER DEFAULT 0,
	ntfy_priority INTEGER DEFAULT 3,
	webhook_url TEXT DEFAULT '',
	pushover_enabled INTEGER DEFAULT 0,
	pushover_priority INTEGER DEFAULT 0,
	ntfy_topic TEXT DEFAULT '',
	proxy_url TEXT DEFAULT '',
	block_filter_entry_rules TEXT NOT NULL DEFAULT '',
	keep_filter_entry_rules TEXT NOT NULL DEFAULT '',
	ignore_entry_updates INTEGER DEFAULT 0,
	UNIQUE (user_id, feed_url),
	FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
	FOREIGN KEY (category_id) REFERENCES categories (id) ON DELETE CASCADE
);

CREATE INDEX feeds_user_category_idx ON feeds (user_id, category_id);
CREATE INDEX feeds_feed_id_hide_globally_idx ON feeds (id, hide_globally);

CREATE TABLE entries (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	user_id INTEGER NOT NULL,
	feed_id INTEGER NOT NULL,
	hash TEXT NOT NULL,
	published_at TIMESTAMP NOT NULL,
	title TEXT NOT NULL,
	url TEXT NOT NULL,
	author TEXT,
	content TEXT,
	status TEXT DEFAULT 'unread' CHECK (status IN ('unread','read','removed')),
	starred INTEGER DEFAULT 0,
	comments_url TEXT DEFAULT '',
	changed_at TIMESTAMP NOT NULL,
	share_code TEXT NOT NULL DEFAULT '',
	reading_time INTEGER NOT NULL DEFAULT 0,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	tags TEXT DEFAULT '[]',
	UNIQUE (feed_id, hash),
	FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
	FOREIGN KEY (feed_id) REFERENCES feeds (id) ON DELETE CASCADE
);

CREATE INDEX entries_feed_id_status_hash_idx ON entries (feed_id, status, hash);
CREATE INDEX entries_id_user_status_idx ON entries (id, user_id, status);
CREATE UNIQUE INDEX entries_share_code_idx ON entries (share_code) WHERE share_code <> '';
CREATE INDEX entries_user_feed_idx ON entries (user_id, feed_id);
CREATE INDEX entries_user_id_status_starred_idx ON entries (user_id, status, starred);
CREATE INDEX entries_user_status_changed_idx ON entries (user_id, status, changed_at);
CREATE INDEX entries_user_status_changed_published_idx ON entries (user_id, status, changed_at, published_at);
CREATE INDEX entries_user_status_created_idx ON entries (user_id, status, created_at);
CREATE INDEX entries_user_status_feed_idx ON entries (user_id, status, feed_id);
CREATE INDEX entries_user_status_published_idx ON entries (user_id, status, published_at);

-- Full-text search backed by FTS5 (BM25 ranking). Replaces the PostgreSQL
-- tsvector "document_vectors" column and GIN index. Column weights (title vs
-- content) are applied at query time via bm25(entries_fts, w_title, w_content).
CREATE VIRTUAL TABLE entries_fts USING fts5(
	title,
	content,
	content='entries',
	content_rowid='id',
	tokenize='unicode61 remove_diacritics 2'
);

CREATE TRIGGER entries_fts_ai AFTER INSERT ON entries BEGIN
	INSERT INTO entries_fts (rowid, title, content)
	VALUES (new.id, new.title, coalesce(new.content, ''));
END;

CREATE TRIGGER entries_fts_ad AFTER DELETE ON entries BEGIN
	INSERT INTO entries_fts (entries_fts, rowid, title, content)
	VALUES ('delete', old.id, old.title, coalesce(old.content, ''));
END;

CREATE TRIGGER entries_fts_au AFTER UPDATE ON entries BEGIN
	INSERT INTO entries_fts (entries_fts, rowid, title, content)
	VALUES ('delete', old.id, old.title, coalesce(old.content, ''));
	INSERT INTO entries_fts (rowid, title, content)
	VALUES (new.id, new.title, coalesce(new.content, ''));
END;

CREATE TABLE entry_tombstones (
	feed_id INTEGER NOT NULL,
	hash TEXT NOT NULL,
	deleted_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (feed_id, hash),
	CHECK (hash <> ''),
	FOREIGN KEY (feed_id) REFERENCES feeds (id) ON DELETE CASCADE
);

CREATE INDEX entry_tombstones_deleted_at_idx ON entry_tombstones (deleted_at);

CREATE TABLE enclosures (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	user_id INTEGER NOT NULL,
	entry_id INTEGER NOT NULL,
	url TEXT NOT NULL,
	size INTEGER DEFAULT 0,
	mime_type TEXT DEFAULT '',
	media_progression INTEGER DEFAULT 0,
	FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
	FOREIGN KEY (entry_id) REFERENCES entries (id) ON DELETE CASCADE
);

CREATE INDEX enclosures_entry_id_idx ON enclosures (entry_id);
CREATE UNIQUE INDEX enclosures_user_entry_url_unique_idx ON enclosures (user_id, entry_id, url);

CREATE TABLE icons (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	hash TEXT NOT NULL,
	mime_type TEXT NOT NULL,
	content BLOB NOT NULL,
	external_id TEXT DEFAULT '',
	UNIQUE (hash)
);

CREATE UNIQUE INDEX icons_external_id_idx ON icons (external_id) WHERE external_id <> '';

CREATE TABLE feed_icons (
	feed_id INTEGER NOT NULL,
	icon_id INTEGER NOT NULL,
	PRIMARY KEY (feed_id, icon_id),
	FOREIGN KEY (feed_id) REFERENCES feeds (id) ON DELETE CASCADE,
	FOREIGN KEY (icon_id) REFERENCES icons (id) ON DELETE CASCADE
);

CREATE TABLE api_keys (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	user_id INTEGER NOT NULL,
	token TEXT NOT NULL,
	description TEXT NOT NULL,
	last_used_at TIMESTAMP,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	UNIQUE (token),
	UNIQUE (user_id, description),
	FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE integrations (
	user_id INTEGER PRIMARY KEY,
	pinboard_enabled INTEGER DEFAULT 0,
	pinboard_token TEXT DEFAULT '',
	pinboard_tags TEXT DEFAULT 'miniflux',
	pinboard_mark_as_unread INTEGER DEFAULT 0,
	instapaper_enabled INTEGER DEFAULT 0,
	instapaper_username TEXT DEFAULT '',
	instapaper_password TEXT DEFAULT '',
	fever_enabled INTEGER DEFAULT 0,
	fever_username TEXT DEFAULT '',
	fever_token TEXT DEFAULT '',
	wallabag_enabled INTEGER DEFAULT 0,
	wallabag_url TEXT DEFAULT '',
	wallabag_client_id TEXT DEFAULT '',
	wallabag_client_secret TEXT DEFAULT '',
	wallabag_username TEXT DEFAULT '',
	wallabag_password TEXT DEFAULT '',
	nunux_keeper_enabled INTEGER DEFAULT 0,
	nunux_keeper_url TEXT DEFAULT '',
	nunux_keeper_api_key TEXT DEFAULT '',
	telegram_bot_enabled INTEGER DEFAULT 0,
	telegram_bot_token TEXT DEFAULT '',
	telegram_bot_chat_id TEXT DEFAULT '',
	googlereader_enabled INTEGER DEFAULT 0,
	googlereader_username TEXT DEFAULT '',
	googlereader_password TEXT DEFAULT '',
	espial_enabled INTEGER DEFAULT 0,
	espial_url TEXT DEFAULT '',
	espial_api_key TEXT DEFAULT '',
	espial_tags TEXT DEFAULT 'miniflux',
	linkding_enabled INTEGER DEFAULT 0,
	linkding_url TEXT DEFAULT '',
	linkding_api_key TEXT DEFAULT '',
	wallabag_only_url INTEGER DEFAULT 0,
	matrix_bot_enabled INTEGER DEFAULT 0,
	matrix_bot_user TEXT DEFAULT '',
	matrix_bot_password TEXT DEFAULT '',
	matrix_bot_url TEXT DEFAULT '',
	matrix_bot_chat_id TEXT DEFAULT '',
	linkding_tags TEXT DEFAULT '',
	linkding_mark_as_unread INTEGER DEFAULT 0,
	notion_enabled INTEGER DEFAULT 0,
	notion_token TEXT DEFAULT '',
	notion_page_id TEXT DEFAULT '',
	readwise_enabled INTEGER DEFAULT 0,
	readwise_api_key TEXT DEFAULT '',
	apprise_enabled INTEGER DEFAULT 0,
	apprise_url TEXT DEFAULT '',
	apprise_services_url TEXT DEFAULT '',
	shiori_enabled INTEGER DEFAULT 0,
	shiori_url TEXT DEFAULT '',
	shiori_username TEXT DEFAULT '',
	shiori_password TEXT DEFAULT '',
	shaarli_enabled INTEGER DEFAULT 0,
	shaarli_url TEXT DEFAULT '',
	shaarli_api_secret TEXT DEFAULT '',
	webhook_enabled INTEGER DEFAULT 0,
	webhook_url TEXT DEFAULT '',
	webhook_secret TEXT DEFAULT '',
	telegram_bot_topic_id INTEGER,
	telegram_bot_disable_web_page_preview INTEGER DEFAULT 0,
	telegram_bot_disable_notification INTEGER DEFAULT 0,
	telegram_bot_disable_buttons INTEGER DEFAULT 0,
	rssbridge_enabled INTEGER DEFAULT 0,
	rssbridge_url TEXT DEFAULT '',
	omnivore_enabled INTEGER DEFAULT 0,
	omnivore_api_key TEXT DEFAULT '',
	omnivore_url TEXT DEFAULT '',
	linkace_enabled INTEGER DEFAULT 0,
	linkace_url TEXT DEFAULT '',
	linkace_api_key TEXT DEFAULT '',
	linkace_tags TEXT DEFAULT '',
	linkace_is_private INTEGER DEFAULT 1,
	linkace_check_disabled INTEGER DEFAULT 1,
	linkwarden_enabled INTEGER DEFAULT 0,
	linkwarden_url TEXT DEFAULT '',
	linkwarden_api_key TEXT DEFAULT '',
	readeck_enabled INTEGER DEFAULT 0,
	readeck_only_url INTEGER DEFAULT 0,
	readeck_url TEXT DEFAULT '',
	readeck_api_key TEXT DEFAULT '',
	readeck_labels TEXT DEFAULT '',
	raindrop_enabled INTEGER DEFAULT 0,
	raindrop_token TEXT DEFAULT '',
	raindrop_collection_id TEXT DEFAULT '',
	raindrop_tags TEXT DEFAULT '',
	betula_url TEXT DEFAULT '',
	betula_token TEXT DEFAULT '',
	betula_enabled INTEGER DEFAULT 0,
	ntfy_enabled INTEGER DEFAULT 0,
	ntfy_url TEXT DEFAULT '',
	ntfy_topic TEXT DEFAULT '',
	ntfy_api_token TEXT DEFAULT '',
	ntfy_username TEXT DEFAULT '',
	ntfy_password TEXT DEFAULT '',
	ntfy_icon_url TEXT DEFAULT '',
	cubox_enabled INTEGER DEFAULT 0,
	cubox_api_link TEXT DEFAULT '',
	discord_enabled INTEGER DEFAULT 0,
	discord_webhook_link TEXT DEFAULT '',
	ntfy_internal_links INTEGER DEFAULT 0,
	slack_enabled INTEGER DEFAULT 0,
	slack_webhook_link TEXT DEFAULT '',
	pushover_enabled INTEGER DEFAULT 0,
	pushover_user TEXT DEFAULT '',
	pushover_token TEXT DEFAULT '',
	pushover_device TEXT DEFAULT '',
	pushover_prefix TEXT DEFAULT '',
	rssbridge_token TEXT DEFAULT '',
	karakeep_enabled INTEGER DEFAULT 0,
	karakeep_api_key TEXT DEFAULT '',
	karakeep_url TEXT DEFAULT '',
	linktaco_enabled INTEGER DEFAULT 0,
	linktaco_api_token TEXT DEFAULT '',
	linktaco_org_slug TEXT DEFAULT '',
	linktaco_tags TEXT DEFAULT '',
	linktaco_visibility TEXT DEFAULT 'PUBLIC' CHECK (linktaco_visibility IN ('PUBLIC','PRIVATE')),
	wallabag_tags TEXT DEFAULT '',
	archiveorg_enabled INTEGER DEFAULT 0,
	karakeep_tags TEXT DEFAULT '',
	linkwarden_collection_id INTEGER,
	readeck_push_enabled INTEGER DEFAULT 0,
	FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE web_sessions (
	id TEXT PRIMARY KEY,
	secret_hash BLOB NOT NULL,
	user_id INTEGER,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	user_agent TEXT NOT NULL DEFAULT '',
	ip TEXT,
	state TEXT NOT NULL DEFAULT '{}',
	CHECK (json_valid(state)),
	FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX web_sessions_created_at_idx ON web_sessions (created_at);
CREATE INDEX web_sessions_user_id_idx ON web_sessions (user_id) WHERE user_id IS NOT NULL;

CREATE TABLE webauthn_credentials (
	handle BLOB PRIMARY KEY,
	cred_id BLOB NOT NULL,
	user_id INTEGER NOT NULL,
	public_key BLOB NOT NULL,
	attestation_type TEXT NOT NULL,
	aaguid BLOB,
	sign_count INTEGER,
	clone_warning INTEGER,
	name TEXT NOT NULL DEFAULT '',
	added_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	last_seen_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	backup_eligible INTEGER,
	backup_state INTEGER NOT NULL DEFAULT 0,
	UNIQUE (cred_id),
	FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE acme_cache (
	key TEXT PRIMARY KEY,
	data BLOB NOT NULL,
	updated_at TIMESTAMP NOT NULL
);
`
