# See https://docs.miniflux.app/

LISTEN_ADDR=0.0.0.0:{{ miniflux_port }}
DATABASE_URL={{ miniflux_db_path | default('/var/lib/miniflux/nanoflux.db') }}

POLLING_FREQUENCY=15
PROXY_IMAGES=http-only

# Run SQL migrations automatically:
RUN_MIGRATIONS=1

CREATE_ADMIN=1
ADMIN_USERNAME={{ miniflux_admin_name }}
ADMIN_PASSWORD={{ miniflux_admin_passwort }}

POLLING_FREQUENCY=10

# Options: https://miniflux.app/miniflux.1.html
