name: Tests
permissions: read-all

on:
  pull_request:
    branches:
    - main
  workflow_dispatch:

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - name: Configure project temporary root
      shell: bash
      run: echo "PROJECT_TMP_BASE=$RUNNER_TEMP" >> "$GITHUB_ENV"
    - name: Checkout
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - name: Set up Go
      uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
      with:
        go-version: '1.27.1'
    - name: Run unit tests with coverage and race conditions checking
      if: matrix.os == 'ubuntu-latest'
      run: make test
    - name: Run unit tests without coverage and race conditions checking
      if: matrix.os != 'ubuntu-latest'
      shell: bash
      run: scripts/test-profile.sh

  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    steps:
    - name: Configure project temporary root
      shell: bash
      run: echo "PROJECT_TMP_BASE=$RUNNER_TEMP" >> "$GITHUB_ENV"
    - name: Checkout
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - name: Set up Go
      uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
      with:
        go-version: '1.27.1'
    - name: Run integration tests
      run: make integration-test
